EXIT IF FRESH;
TRY;
ALTER TABLE sessions RENAME COLUMN `system` TO `system_session`;
UPDATE sessions SET `system_session` = 0 WHERE `system_session` IS NULL;
CATCH;
TRY;
ALTER TABLE resources RENAME COLUMN `system` TO `system_resource`;
UPDATE resources SET `system_resource` = 0 WHERE `system_resource` IS NULL;
CATCH;
TRY;
ALTER TABLE permissions RENAME COLUMN `system` TO `system_permission`;
UPDATE permissions SET `system_permission` = 0 WHERE `system_permission` IS NULL;
CATCH;
