EXIT IF FRESH;
TRY;
alter table assignable_resources drop foreign key `assignable_resources_cascade_1`;
alter table assignable_resources add CONSTRAINT `assignable_resources_cascade_1` FOREIGN KEY (`realm_id`) REFERENCES `realms` (`resource_id`) ON DELETE CASCADE;
alter table auth_schemes drop foreign key `auth_schemes_cascade_1`;
alter table auth_schemes add CONSTRAINT `auth_schemes_cascade_1` FOREIGN KEY (`realm_id`) REFERENCES `realms` (`resource_id`) ON DELETE CASCADE;
alter table count_keys drop foreign key `count_keys_cascade_1`;
alter table count_keys add CONSTRAINT `count_keys_cascade_1` FOREIGN KEY (`realm_id`) REFERENCES `realms` (`resource_id`) ON DELETE CASCADE;
alter table html_templates drop foreign key `html_templates_cascade_1`;
alter table html_templates add CONSTRAINT `html_templates_cascade_1` FOREIGN KEY (`realm_id`) REFERENCES `realms` (`resource_id`) ON DELETE CASCADE;
alter table interface_state drop foreign key `interface_state_cascade_1`;
alter table interface_state add CONSTRAINT `interface_state_cascade_1` FOREIGN KEY (`realm_id`) REFERENCES `realms` (`resource_id`) ON DELETE CASCADE;
alter table jobs drop foreign key `jobs_cascade_1`;
alter table jobs add CONSTRAINT `jobs_cascade_1` FOREIGN KEY (`realm_id`) REFERENCES `realms` (`resource_id`) ON DELETE CASCADE;
alter table ous drop foreign key `ous_cascade_1`;
alter table ous add CONSTRAINT `ous_cascade_1` FOREIGN KEY (`realm_id`) REFERENCES `realms` (`resource_id`) ON DELETE CASCADE;
alter table password_history drop foreign key `password_history_cascade_1`;
alter table password_history add CONSTRAINT `password_history_cascade_1` FOREIGN KEY (`principal_resource_id`) REFERENCES `principals` (`resource_id`) ON DELETE CASCADE;
alter table principals drop foreign key `principals_cascade_1`;
alter table principals add CONSTRAINT `principals_cascade_1` FOREIGN KEY (`realm_id`) REFERENCES `realms` (`resource_id`) ON DELETE CASCADE;
alter table profiles drop foreign key `profiles_cascade_1`;
alter table profiles add CONSTRAINT `profiles_cascade_1` FOREIGN KEY (`realm_resource_id`) REFERENCES `realms` (`resource_id`) ON DELETE CASCADE;
alter table realm_attribute_categories drop foreign key `realm_attribute_categories_cascade_1`;
alter table realm_attribute_categories add CONSTRAINT `realm_attribute_categories_cascade_1` FOREIGN KEY (`realm_id`) REFERENCES `realms` (`resource_id`) ON DELETE CASCADE;
alter table roles drop foreign key `roles_cascade_1`;
alter table roles add CONSTRAINT `roles_cascade_1` FOREIGN KEY (`realm_id`) REFERENCES `realms` (`resource_id`) ON DELETE CASCADE;
alter table secret_keys drop foreign key `secret_keys_cascade_1`;
alter table secret_keys add CONSTRAINT `secret_keys_cascade_1` FOREIGN KEY (`realm_id`) REFERENCES `realms` (`resource_id`) ON DELETE CASCADE;
alter table sessions drop foreign key `FK7p9rpoydclkkb7kusskh1c4dp`;
alter table sessions drop foreign key `FKaddh4m6cktcbrwkh3sb66re9r`;
alter table sessions drop foreign key `FKln61w77s0lqwskg77o65bc4cd`;
alter table sessions drop foreign key `FKlvxqavua1llyyic8jf9gkv790`;
alter table sessions drop foreign key `FKnq5ln1ch01alqw2x262ih21u1`;
alter table sessions add CONSTRAINT `FK7p9rpoydclkkb7kusskh1c4dp` FOREIGN KEY (`realm_id`) REFERENCES `realms` (`resource_id`) ON DELETE CASCADE;
alter table sessions add CONSTRAINT `FKaddh4m6cktcbrwkh3sb66re9r` FOREIGN KEY (`impersonating_principal_id`) REFERENCES `principals` (`resource_id`) ON DELETE CASCADE;
alter table sessions add CONSTRAINT `FKln61w77s0lqwskg77o65bc4cd` FOREIGN KEY (`principal_id`) REFERENCES `principals` (`resource_id`) ON DELETE CASCADE;
alter table sessions add CONSTRAINT `FKlvxqavua1llyyic8jf9gkv790` FOREIGN KEY (`authentication_scheme`) REFERENCES `auth_schemes` (`resource_id`) ON DELETE CASCADE;
alter table sessions add CONSTRAINT `FKnq5ln1ch01alqw2x262ih21u1` FOREIGN KEY (`current_realm_id`) REFERENCES `realms` (`resource_id`) ON DELETE CASCADE;
alter table ssl_certificates drop foreign key `ssl_certificates_cascade_1`;
alter table ssl_certificates add CONSTRAINT `ssl_certificates_cascade_1` FOREIGN KEY (`realm_id`) REFERENCES `realms` (`resource_id`) ON DELETE CASCADE;
alter table tasks drop foreign key `tasks_cascade_1`;
alter table tasks add CONSTRAINT `tasks_cascade_1` FOREIGN KEY (`realm_id`) REFERENCES `realms` (`resource_id`) ON DELETE CASCADE;
alter table uploaded_files drop foreign key `uploaded_files_cascade_1`;
alter table uploaded_files add CONSTRAINT `uploaded_files_cascade_1` FOREIGN KEY (`realm_id`) REFERENCES `realms` (`resource_id`) ON DELETE CASCADE;
CATCH;
