EXIT IF FRESH;
TRY;
UPDATE sessions SET `system` = 0 WHERE `system` IS NULL;
ALTER TABLE sessions RENAME COLUMN `system` TO `system_session`;
CATCH;
TRY;
UPDATE resources SET `system` = 0 WHERE `system` IS NULL;
ALTER TABLE resources RENAME COLUMN `system` TO `system_resource`;
CATCH;
TRY;
UPDATE permissions SET `system` = 0 WHERE `system` IS NULL;
ALTER TABLE permissions RENAME COLUMN `system` TO `system_permission`;
CATCH;
